### ISSUE TITLE
ArgoCD setup 작성

### ISSUE THREAD

**Issue by junha-ahn** [f-lab-clone/ticketing-infra#5]
# Todo

- [x] `provider helm` setup
- [x] `helm_release` 를 통해 argoCD setup
- [x] application.yaml 작성
     -  [app-of-apps pattern](https://argo-cd.readthedocs.io/en/stable/operator-manual/declarative-setup/)

**Comment by junha-ahn** [comment]
setup 
- https://medium.com/@rvisingh1221/setup-argocd-in-aws-eks-cluster-using-terraform-ee2f064d057c

what is "heml_release"
- https://registry.terraform.io/providers/hashicorp/helm/latest/docs/resources/release
- https://getbetterdevops.io/terraform-with-helm/

**Comment by junha-ahn** [comment]
ArgoCD local 포트포워딩 후 접속 법

```shell
aws eks update-kubeconfig --region ap-northeast-2 --name ticketing-main-cluster

kubectl -n argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.password}" | base64 -d; echo

kubectl port-forward svc/morgo-argocd-server -n argocd 8080:443
- codespace => port => port protocol 변경 => https
```
